version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-latest
      - build-1.12
      - build-1.13
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-latest
      - build-1.12
      - build-1.13

jobs:
  build-latest: &build-template
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run: uname -a
      - run: go version
      - run:
          name: Install tcpdump build dependencies
          command: |
                    sudo apt-get update
                    sudo apt-get install -y libusb-1.0-0-dev
                    sudo apt-get install -y libdbus-glib-1-dev
                    sudo apt-get install -y libbluetooth-dev
                    sudo apt-get install -y libnl-genl-3-dev
                    sudo apt-get install -y libibverbs-dev
                    sudo apt-get install -y libssl-dev
                    sudo apt-get install -y libssl1.1
                    sudo apt-get install -y libdnet-dev
                    sudo apt-get install -y libsmi2-dev
                    sudo apt-get install -y libcap-ng-dev
                    sudo apt-get install -y libpcap-dev
      - run:
          name: Build latest tcpdump
          command: |
                    cd ..
                    git clone --depth 3 --branch=master --quiet git://github.com/the-tcpdump-group/tcpdump.git
                    cd tcpdump
                    ./configure --prefix=/tmp
                    make
                    sudo make install
      - run: go vet ./...
      - run:
          name: Run go tests
          environment:
            GOTESTSUM_JUNITFILE: /tmp/test-reports/gotests/junit.xml
          command: |
                    mkdir -p /tmp/test-reports/gotests
                    PATH=/tmp/sbin:$PATH gotestsum
      - run:
          name: codecov
          command: |
                    PATH=/tmp/sbin:$PATH go test -race -coverprofile=coverage.txt -covermode=atomic
                    bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /tmp/test-reports

  build-1.12:
    <<: *build-template
    docker:
      - image: circleci/golang:1.12

  build-1.13:
    <<: *build-template
    docker:
      - image: circleci/golang:1.13
